### PR TITLE
Add support for PHP 8.1

### PR DESCRIPTION
**Pull request by osrecio**
- [x] There is an issue ticket which accompanies my PR: https://github.com/weprovide/valet-plus/issues/600
- [x] I have followed the [guidelines for contributing](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md).
- [x] I have checked that there aren't other open [pull requests](https://github.com/weprovide/valet-plus/pulls) for the same issue ticket.
- [x] I have formatted my code with the [PSR-2](http://www.php-fig.org/psr/psr-2/) coding style before submitting my PR.
-----

**I have read the contribution guidelines and am targeting the branch `<YOUR_TARGET_BRANCH>`:**  
Because this is a Bug Fix which is Backwards Compatible.  
Because this is a Feature which is not Backwards Compatible.  
Because this is a Deprecation which is Backwards Compatible.  
etc...

**Changelog entry:**  
Short description of your work as explained by: [Keep A Changelog](https://keepachangelog.com).

### CODE REVIEW

**Comment by osrecio** [comment]
@mischabraam I think is ready to merge if all looks ok for you.

I was waiting for the resolution of this PR: https://github.com/henkrehorst/homebrew-php/pull/160 but we can't wait more :) (I don't know if we can change the repo of php like regular valet)

Greetings and thanks!

**Comment by PieterCappelle** [comment]
Hello, when will this be merged? Thanks! Great PR.

**Comment by mischabraam** [comment]
Thanks. I'm looking into getting this in the 2.4.0-beta release.

**Comment by mischabraam** [comment]
Support php8.1 (with deprecated suppression) now available in 2.4.0-beta4, based on your changes. Thanks!

**Pull request closed without merging**
