### PR TITLE
re-style page 404 error

### PR DESCRIPTION
**Pull request by salkhwlani**
ezgif com-video-to-gif

### CODE REVIEW

**Comment by SanderAtom** [comment]
Looks good 👍

**Comment by Neodork** [comment]
@yemenifree Could you target the 2.x branch? I'll be willing to merge this despite it being old and not adhering to the new 2.0 contributor guidelines.

**Comment by yemenifree** [comment]
@Neodork I'll check it tomorrow :)

**Comment by EHLOVader** [comment]
I was revisiting this because I thought it would be really nice to improve the 404 page too. I'd like to add functionality to it if possible. Full dashboard, with link to MailHog on top. Icons for drivers, etc. I think this PR would be a great place to start from.

**Pull request closed without merging**
