### PR TITLE
Enable URL rewrite in Magento2 configure

### PR DESCRIPTION
**Pull request by barryvdh**
Not a fix, but at least easy workaround for #66 

Not sure if we still need this if we fix it, but it should be a good default, right?

### CODE REVIEW

**Comment by timneutkens** [comment]
I guess it should be documented here: https://github.com/weprovide/valet-plus#magento-2

**Comment by barryvdh** [comment]
So do you want me to update the Readme? Otherwise good?

**Comment by timneutkens** [comment]
Yep 👍

**Comment by timneutkens** [comment]
I'll do it 👌

**Pull request merged**
