### PR TITLE
pin mysql to 5.7

### PR DESCRIPTION
**Pull request by agjmills**
https://github.com/weprovide/valet-plus/issues/197

### CODE REVIEW

**Comment by Neodork** [comment]
@agjmills Thanks for the PR. Can you squash your commits into one? Other then squash LGTM. @samgranger Review please after squash.

**Comment by agjmills** [comment]
@Neodork @samgranger squashed as requested

**Comment by Neodork** [comment]
@samgranger LGTM, review and merge please.

**Comment by samgranger** [comment]
Agreed, looks good. Thanks for your PR @agjmills, merged! We will add this to a new release soon.

**Pull request merged**
