### PR TITLE
PHP 5.6 and 7.0 EOL changes

### PR DESCRIPTION
**Pull request by Neodork**
PR for https://github.com/weprovide/valet-plus/issues/298

### CODE REVIEW

**Comment by regularlabs** [comment]
Is `valet use` broken now?
I have php 7.2 installed (and am using that), but `valet use 7.2` gives an error.
phpuse

PS: this is after updating valet-plus to 1.0.25

**Comment by kalinstanchev** [comment]
@regularlabs Can you proceed to do `brew link valet-php@7.2`? And then `valet fix`?

**Comment by regularlabs** [comment]
`
brew link valet-php@7.2
Error: No such keg: /usr/local/Cellar/valet-php@7.2
`

**Comment by regularlabs** [comment]
And when doing a `valet fix`:
```
...
==> Searching taps...
Error: No formulae found in taps.

Error: No such keg: /usr/local/Cellar/valet-php@7.1

Error: No such keg: /usr/local/Cellar/valet-php@7.1

Please check your linked php version, you might need to restart your terminal!
Linked PHP should be php 7.1:
PHP 7.2.13 (cli) (built: Dec  7 2018 10:41:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by regularlabs** [comment]
I did a `brew upgrade` and also a `brew install php@7.1`.
So now: `brew list | grep php`
```
php
php@7.1
php@7.2
```
Where `php` is php 7.3 (brew default).

`php -v` returns `PHP 7.2.14`.

Any of these will result in a `Unable to determine linked PHP.` error:
```
valet use 7.1
valet use 7.2
valet use 7.3
```

**Comment by kalinstanchev** [comment]
Yes, so now can you do `brew tap henkrehorst/php`? and then `brew link valet-php@7.2`?

**Comment by regularlabs** [comment]
```
➜  brew tap henkrehorst/php
==> Tapping henkrehorst/php
Cloning into '/usr/local/Homebrew/Library/Taps/henkrehorst/homebrew-php'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 15 (delta 5), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
Tapped 5 formulae (49 files, 139KB).
➜  brew link valet-php@7.1
Error: No such keg: /usr/local/Cellar/valet-php@7.1
➜  j brew link valet-php@7.2
Error: No such keg: /usr/local/Cellar/valet-php@7.2
```

**Comment by kalinstanchev** [comment]
Sorry forgot to mention instead `brew link valet-php@7.2` use `valet use 7.2`

**Comment by regularlabs** [comment]
I don't get it.
It seems `/usr/local/Cellar/valet-php@7.1` is created now. But 7.2 and 7.3 are not.
So would that be an issue with `henkrehorst/php`?

**Comment by regularlabs** [comment]
```
➜  brew link valet-php@7.1
Warning: valet-php@7.1 is keg-only and must be linked with --force

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/valet-php@7.1/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/valet-php@7.1/sbin:$PATH"' >> ~/.zshrc

➜  brew link valet-php@7.2
Error: No such keg: /usr/local/Cellar/valet-php@7.2

➜  brew link valet-php@7.3
Error: No such keg: /usr/local/Cellar/valet-php@7.3
```

**Comment by kalinstanchev** [comment]
Basically because valet-plus are no longer use the `homebrew/php` because of deprecated php 5.6. So in order to link the valet-php@7.1 you need to force it. Then change it to valet use 7.2. This will fix automatically the php selected is will be downloading the valet-php@7.2. The same for the 7.3. By default valet uses php 7.1.

**Comment by regularlabs** [comment]
> So in order to link the valet-php@7.1 you need to force it. Then change it to valet use 7.2.
Sorry, don't know what you mean by that. Force it how, and how change it to 7.2?

**Comment by regularlabs** [comment]
```
➜  brew link valet-php@7.1 --force
Linking /usr/local/Cellar/valet-php@7.1/7.1.25... 131 symlinks created
```
I guess you mean that.

But still:
```
➜ brew link valet-php@7.2 --force
Error: No such keg: /usr/local/Cellar/valet-php@7.2
```

**Comment by regularlabs** [comment]
`/usr/local/Cellar/`
image

**Comment by kalinstanchev** [comment]
No, I mean 7.1, now try to do `valet use 7.2`

**Comment by regularlabs** [comment]
Ah, now `valet use 7.2` starts installing php 7.2.
Same for 7.3.

So guess that solves it.
(Although I have no idea why :) )

PS: It would be good if the `brew upgrade` or `valet fix` would have taken care of all this.
Seems like the upgrade of valet-plus is just not doing what it should.

**Comment by kalinstanchev** [comment]
Yeah, we are adding checks and fixing this issue, we are sorry for any inconvenience!

**Comment by sajidunnar** [comment]
I want to use use Php 5.6 but its not working as valet fix produce this

[PECL] Checking pear config...
Checking php 5.6...
    Skipping 5.6, Pear config path could not be found at: /usr/local/etc/valet-php/5.6/pear.conf
Checking php 7.0...
    Skipping 7.0, Pear config path could not be found at: /usr/local/etc/valet-php/7.0/pear.conf
Checking php 7.1...
    Setting pear config php_dir directive to: /usr/local/share/valet-pear@7.1
    Setting pear config doc_dir directive to: /usr/local/share/valet-pear@7.1/doc

**Pull request merged**
