### PR TITLE
Update for Pimcore >= 5.5

### PR DESCRIPTION
**Pull request by cmaerz**
Pimcore changed his file structure. This changes should fix this.

### CODE REVIEW

**Comment by samgranger** [comment]
Thanks for this PR. What about older installations? Can we add support for both or put this in a seperate driver?

**Comment by cmaerz** [comment]
Hi Sam, maybe we can add an PimcoreOldValetDriver.php  with the old Version of the driver. The PimcoreValetDriver.php should always support the newest version imo.

**Comment by Serializator** [comment]
@cmaerz, I created a draft pull request after I read about the backward compatibility issue in this PR.
I would like to know what you think, because I myself have never worked with Pimcore, yet.

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Pull request closed without merging**
