### PR TITLE
Added drivers for Neos and TYPO3

### PR DESCRIPTION
**Pull request by zelgerj**

### CODE REVIEW

**Comment by samgranger** [comment]
I haven't had the chance to test this yet, but will try to get this merged this week after testing. Looks good!

**Comment by zelgerj** [comment]
did you already have the possibility to test it?

**Comment by zelgerj** [comment]
Meanwhile we forked your repo to techdivision/valet-plus. Please feel free to merge any implementation we do to your repo. Just let me know if you've any question / suggestions. Thanks

**Comment by steffenbrand** [comment]
The TYPO3 driver needs to be merged! :)

**Comment by samgranger** [comment]
So sorry that this took so long, I have merged this change - I will be merging a few other changes tomorrow and will create a new release!

**Pull request merged**
