### PR TITLE
We should be checking that we aren't using a subdomain install

### LINKED ISSUE #429: Bug: Wordpress Multisite Subdirectory Driver Not Working
- [✅] I've checked the issue queue and could not find anything similar to my bug.
- [✅] I'm on the latest version of valet-plus (`valet --version`): `1.0.29`
- [✅] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When browsing a site within a Wordpress Multisite install no assets are loaded

**What was supposed to happen?**
When browsing a site that uses subdirectories as opposed to subdomains, the subdirectory should be stripped from the URL for all assets.

**What actually happened?**
The subdirectory isn't stripped

**How to reproduce this?**
Have a WordPress Multisite install, setup a new site that uses subdirectories. Browse the new site.

**What is the solution?**
I will be creating a Pull Request with the fix.

### PR DESCRIPTION
**Pull request by RMcLeod79**
Fixes #429 
If we are using a subdomain install then this driver isn't needed to server the site

### CODE REVIEW

**Comment by Neodork** [comment]
@RMcLeod79 Are you sure this doesn't harm any other multisite setups?

**Comment by RMcLeod79** [comment]
@Neodork This driver is only for subdirectory multisite configurations and this fix makes sure they work, it doesn't affect other multisite setups. I have targeted 2.x as requested.

**Comment by jeremyfelt** [comment]
I've submitted another PR in #441 that addresses this by looking only for a `true` definition of `SUBDOMAIN_INSTALL` and then bailing if it is found. We can't check `false` as that is the assumed default if no constant is provided.

**Comment by Neodork** [comment]
@RMcLeod79 Do you agree with the PR from @jeremyfelt ?

**Comment by RMcLeod79** [comment]
@Neodork The PR from @jeremyfelt is better than mine

**Comment by Neodork** [comment]
@RMcLeod79 Oke thanks for collaborating appreciate the honest input. We'll go with his PR I'll merge it into `2.x` as soon as @jeremyfelt targets the correct branch.

**Pull request closed without merging**
