### PR TITLE
[FEATURE] Use mkcert to generate SSL certificates

### PR DESCRIPTION
**Pull request by titouanmathis**
- [x] I have followed the [guidelines for contributing](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md).
- [x] I have checked that there aren't other open [pull requests](https://github.com/weprovide/valet-plus/pulls) for the same issue ticket.
- [x] I have formatted my code with the [PSR-2](http://www.php-fig.org/psr/psr-2/) coding style before submitting my PR.

---

**I have read the contribution guidelines and am targeting the branch `2.x`:**  
Because this is a Feature (with a bugfix) which is Backwards Compatible.

**Changelog entry:**  

### Changed
- Use `mkcert` to generate SSL certificates (52ff899)
- Delete related SSL certificates and Nginx configuration when using `valet unlink [name]` (96a6b1c)

### Fixed
- Fix the certificates getter to correctly display secured site with `valet links` (2f6c958)

---

This PR introduces the usage of [`mkcert`](https://github.com/FiloSottile/mkcert) to generate the SSL certificates when securing a site:

- `mkcert` generates valid certificates for all browsers, including Firefox which does not consider the ones created with `openssl` valid
- it simplifies the process of creating certificates as `mkcert` handles the creation and the trust parts

I am not really sure about myself for the `Mkcert` class added as maybe the `mkcert` installation should be handled by the `DevTools` class.

### CODE REVIEW

**Comment by Neodork** [comment]
@titouanmathis Thanks for your PR. This looks very interesting and I am willing to merge it as a MINOR version (feature). Are you sure you unlink method is backward compatible? Can you maybe add tests to azure pipeline for MKCERT? 

I think using devtools is oke if you only require the binary. If you need to do more advanced stuff with the binary you might want to separate into your own class.

**Comment by Neodork** [comment]
@titouanmathis This is failing can you check the CI/CD?

**Comment by viktorbijlenga** [comment]
@mischabraam Would it be possible to trigger the CI/CD check here again? Then it might be easier to figure out what's missing on this PR at the moment.

**Pull request closed without merging**
