### PR TITLE
Update

### PR DESCRIPTION
**Pull request by lewisvoncken**
- [ ] There is an issue ticket which accompanies my PR: <Your-Issue-Link>.
- [ ] I have followed the [guidelines for contributing](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md).
- [ ] I have checked that there aren't other open [pull requests](https://github.com/weprovide/valet-plus/pulls) for the same issue ticket.
- [ ] I have formatted my code with the [PSR-2](http://www.php-fig.org/psr/psr-2/) coding style before submitting my PR.
-----

**I have read the contribution guidelines and am targeting the branch `master`:**  
Because this is a Feature with small Bug Fixes is Backwards Compatible.  

**Changelog entry:**  
Short description of your work as explained by: [Keep A Changelog](https://keepachangelog.com).
### Changed
- Enabled apc by default because it is working correctly and makes it possible to also run Akeneo. See this codeblog for more information https://codeblog.experius.nl/install-akeneo-localhost/ 
- Updated the Xdebug Max Nesting Level to 2000
- Updated the Memory Limit from 2G to 16G
- Set the mysql setting column-statistics to zero for MySQL 5.7 support

### Added
- Added support for a custom elasticsearch.php
- Added Blackfire Support *Wiki changes are added in a patch file*

[blackfire_wiki.txt](https://github.com/weprovide/valet-plus/files/4179355/blackfire_wiki.txt)

### CODE REVIEW

**Comment by SanderAtom** [comment]
Hi @lewisvoncken,

Thanks for helping improving Valet+! :)
Just a few things that caught my eye:

1. Can you please target the `2.x` branch if these changes are backwards compatible?

2. Did you read this issue #49 regarding disabling APCu? We should at least test some of the problems described there to see if those are still an issue before enabling it again.

3. I agree with upping the memory limit but not everyone has 16GB of ram, I would vote for 4 or 8GB. Personally I have a `/usr/local/etc/valet-php/[version]/conf.d/zz-local.ini` file with my custom memory limit (all ini's are loaded inside the `conf.d` directories and this overrides the default from valet+).

4. `Set the mysql setting column-statistics to zero for MySQL 5.7 support`
From what I read this is to access a MySQL 5.7 database with the MySQL 8.0 mysql-client, right? Can you explain why this is needed, maybe for a program like MySQL Workbench? If this happens with a normal `mysqldump` from your command line, you might be using the wrong mysql-client by accident?

5. Blackfire support
I think we need to add some test cases for this and if possible shasum checks on specific downloads like we have for the magerun(2) and drush command line tools.

When I get some more time I can test the changes locally like installing Blackfire and the issues with apcu/php-fpm.

**Comment by lewisvoncken** [comment]
Hi @SanderAtom ,

As a reply on your todos:

1. Can you please target the 2.x branch if these changes are backwards compatible? **done**
2. Did you read this issue #49 regarding disabling APCu? **I have read it and I have been working with it since 8 march 2019 and it is working correctly**
3. I agree with upping the memory limit but not everyone has 16GB of ram, I would vote for 4 or 8GB. Personally I have a /usr/local/etc/valet-php/[version]/conf.d/zz-local.ini file with my custom memory limit (all ini's are loaded inside the conf.d directories and this overrides the default from valet+). **has been changed to 4G**
4. Set the mysql setting column-statistics to zero for MySQL 5.7 support
From what I read this is to access a MySQL 5.7 database with the MySQL 8.0 mysql-client, right? Can you explain why this is needed, maybe for a program like MySQL Workbench? If this happens with a normal mysqldump from your command line, you might be using the wrong mysql-client by accident? **I also had this issue on a Google Cloud server so I recommend to apply this**
5. Blackfire support **Have you had time to test this?**

Let me know if I can do anything more because I would love these changes to be merged!

**Comment by SanderAtom** [comment]
Hi @lewisvoncken thank you for your reply. I would suggest to cut this PR up into smaller separate PRs because there are too many different bugfixes and features together to easily review and merge. This would speed up the process of getting some smaller features/bugfixes through without something blocking everything like Blackfire which might take longer to test.

**Comment by lewisvoncken** [comment]
@SanderAtom I am splitting up the PR

**Comment by lewisvoncken** [comment]
@SanderAtom 
I have created separate PRs:

#503 Mysql 5.7 fix
#498 Additional PHP Scripts
#500 enable apc for Akeneo
#501 Upgrade memory limit
#502 xdebug.max_nesting_level

I will close this pr for now

**Pull request closed without merging**
