### PR TITLE
[refactoring][cleanup] Mysql Cli

### PR DESCRIPTION
**Pull request by yemenifree**
for now, refactoring code of current commands, but I have many things to do after merging this PR.

TODO (Mysql) after merge PR:

- write test unit for MySQL commands.
- add the ability to change root password via Valet command.
- export all databases.

any suggestions are welcome

### CODE REVIEW

**Comment by SanderAtom** [comment]
Hi @yemenifree is there a reason you removed the gzipping of the sql files when importing and exporting?
Also you've changed the date format to `DateTime::Atom` which outputs like: `2017-11-23T17:05:48+01:00` which is a little annoying for filenames in the command line as it has to escape all the semicolons `:` eg: `project-2017-11-23T17\:05\:48+01\:00.sql`.

**Comment by yemenifree** [comment]
@SanderAtom sorry about that, it's my mistake.

because my local version doesn't include your PR #62

thanks for the attention.

**Comment by SanderAtom** [comment]
Nice, no problem. I haven't tested the code yet, but I scanned through it and it looks good.

**Comment by SanderAtom** [comment]
I've started testing the changes and one thing I noticed is that I see a warning when you run `valet db import [file]` when the database already exists but the operation is still succesful:
```
$ valet db import file.sql
Can't create database 'testing123'; database exists
Importing database...
718KiB 0:00:00 [ 885KiB/s] [=================>] 100%
```
Before this message was suppressed. Maybe we should refactor this logic so it's checking for an existing database and asks if you want to continue?

But other than that everything seems to work fine without errors.

**Comment by yemenifree** [comment]
@SanderAtom I edit query of creating database to prevent show error if already exists, and add confirm questions to import command,

> there are more thing prevent create multi-connection every time `getConnection` is called.

**Comment by samgranger** [comment]
Thanks yemenifree, I will try and test this tomorrow (cannot guarantee I will get round to do so but thanks for the changes so far!). Will update asap.

**Comment by samgranger** [comment]
Merged! Sorry that this took a while.

**Pull request merged**
