### PR TITLE
[FIX] Set new default ES version and remove unsupported

### PR DESCRIPTION
**Pull request by zcuric**
- [x] There is an issue ticket which accompanies my PR: #513 .
- [x] I have followed the [guidelines for contributing](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md).
- [x] I have checked that there aren't other open [pull requests](https://github.com/weprovide/valet-plus/pulls) for the same issue ticket.
- [x] I have formatted my code with the [PSR-2](http://www.php-fig.org/psr/psr-2/) coding style before submitting my PR.
-----

**I have read the contribution guidelines and am targeting the branch `master`:**  
Because this is a Bug Fix which is Backwards Compatible.

### CODE REVIEW

**Comment by Neodork** [comment]
@mischabraam @samgranger Can you check this? since it's Elastic.

**Comment by Neodork** [comment]
@zcuric Can you please target `2.x` instead of master.

**Comment by Leland** [comment]
Not specific to this PR, but the wiki deserves to get some docs around this. Maybe making [Switching PHP versions](https://github.com/weprovide/valet-plus/wiki/Switching-PHP-versions) generic, to say "Switching versions."

**Comment by zcuric** [comment]
@Neodork done.

**Comment by mischabraam** [comment]
Adding 7.6 is already in the 2.x branch. Please fix your conflicts.
I agree with setting 7.6 as default.
I agree with removing 2.4 and 5.6, however that means this is NOT backwards compatible.

**Comment by Neodork** [comment]
@zcuric Can you rabase you changes from `2.x`? There is a lot of stuff that's coming along with the master branch.


@mischabraam Is this really non-BC? To me it feels like it requires an upgrade path (E.G: use the correct suffix for you elasticsearch version). Lets say you have an old version installed and we run this, that old version would keep working if you use the correct suffixed command right? If so this change would be MINOR. Otherwise we'll need to merge towards Master and the change would be MAJOR and has to wait for the next MAJOR release.

**Comment by zcuric** [comment]
@Neodork done.

**Comment by zcuric** [comment]
@mischabraam Conflicts resolved. 
@Neodork Rebased.

**Comment by zcuric** [comment]
@Neodork the oldest version of Elasticsearch on homebrew is 6.8. So people are forced to upgrade anyway because of homebrew.

**Comment by Neodork** [comment]
@zcuric Thanks for you answer and rebase! I'll await the CI/CD and if it's all green I will merge this as MINOR change. You can expect this to be in the next `2.1.0` version. Thanks for your PR and contribution to Valet+.

**Comment by zcuric** [comment]
@Neodork You are welcome. I'll try to contribute more in the future.

**Review by mischabraam — APPROVED** [review]
Nice, thanks for helping!

**Comment by Neodork** [comment]
**Changelog entries:**
- Removed support for Elasticsearch 2.4
- Removed support for Elasticsearch 5.6
- Removed support for Elasticsearch 7.6

- Added support for Elasticsearch 7.8

**Pull request merged**
