### PR TITLE
[FIX] assign correct YML version compatibility to PHP 7.0

### PR DESCRIPTION
**Pull request by amarroni**
YAML version minimal compatibility changed to PHP 7.1.0, was needed to determine the YAML version will working without problems.
Based on discussion on Channel Slack, the version is 2.0.4 (provide @Neodork thank you.)

Added. that version to 7.0 -> 2.0.4

### CODE REVIEW

**Comment by Neodork** [comment]
@amarroni Would you mind rebasing your branch from `2.x`? Otherwise I'll have to cherry pick this and you'll lose credits.

**Comment by amarroni** [comment]
Hi @Neodork how are you?

What to you want to do?

Best,

**Comment by amarroni** [comment]
#541 DONE!

**Comment by Neodork** [comment]
@amarroni Thanks for the effort! Your work is merged and will be included in the next release. I really appreciate the quick response on my request. Thanks again. 

You can check your work here: https://github.com/weprovide/valet-plus/commits/2.x

**Pull request closed without merging**
