### PR TITLE
Allow use of symphony/process v4

### PR DESCRIPTION
**Pull request by ddb87**

### CODE REVIEW

**Comment by Neodork** [comment]
Hi, would you please elaborate why this change is necessary?

**Comment by ddb87** [comment]
To avoid conflict with (global) laravel/installer when installing valet+ as global dependency.

**Comment by Neodork** [comment]
@samgranger Review please, LGTM.

**Comment by samgranger** [comment]
Hi @ddb87 - I unfortunately have to revert this change due to v4 breaking PHP 5.6 compatibility.

**Comment by tenyard** [comment]
Whilst I understand the "technical" reasoning behind reverting the change, it seems somewhat counterintuitive to me.

Up until relatively recently I was actively working on and maintaining 5.6 projects so I certainly empathise with those who have to deal with the associated pain, especially those who it's beyond their power to control for whatever reason, but I'm also just as familiar with the fact that when you're running something as old as 5.6 (what, about 3 years old now??) that you have to endure some pain and a not insignificant number of workarounds.

The laravel installer isn't old and is currently a relatively significant part of the php universe, not to mention the somewhat ironic fact that the guys who created it also created the OG Valet and essentially now you're saying that Valet+ and the Laravel Installer can't be installed together globally. 

Wouldn't it make more sense to include the 4.* constraint as the valet does and find an alternate workaround for the 5.6 functionality?  

I guess some of it (maybe a lot or even all of it) comes down to what you guys are trying to acheive with Valet+ but personally I don't recall there being a great emphasis on the use of 5.6 on the front page of the repo. If the legacy stuff is your goal that's perfectly fine and would make the decision totally understandable, but if that is the case maybe you want to make that a little clearer up front on the repo.

If you're aiming a little broader then I can't see how this ends up benefitting the most people. 

Please don't misconstrue this as flat out criticism, all the contributors have done some great work here, of that there can be no doubt, however to me this seemed like a particular odd decision to make, especially given the effect it has.

**Comment by tenyard** [comment]
OK, figured I should at least make an attempt at sorting it out myself and in the interim I have a workaround. 

You can get the two (valet+ and laravel installer) to install together globally but it requires nuking your current composer global setup (~/.composer/composer.json and the vendor directory) then manually installing valet+ FIRST

`composer global require weprovide/valet-plus` 

THEN install the laravel installer and other global dependencies.

As it stands now the laravel-installer will install OK and use the 3.* version of symfony/process 

In my case all the other dependencies worked but YMMV

Hope, in the meantime, that helps out anyone else encountering the same issue.

**Pull request merged**
